name: PR Checks

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run flake8
        run: flake8 tasklin --max-line-length=90

      - name: Run black (check only)
        run: black --check tasklin --line-length=90